name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
            - os: ubuntu-latest
              lib: libusbdmx.so
            - os: windows-latest
              lib: usbdmx64.dll
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Install missing packages
      run: sudo apt-get update && sudo apt-get install libudev-dev -y
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - name: Build
      run: make ${{ matrix.lib }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: DMXforDummies-${{ runner.os }}-${{ github.job }}
        path: |
          libusbdmx.so
          libusbdmx.dylib
          usbdmx64.dll
          *.o
          **/*.o
          50-usbdmx.rules
          README.md
          LICENSE*.txt