name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-15-intel, macos-latest]
        include:
            - os: ubuntu-latest
              lib: libusbdmx.so
            - os: ubuntu-24.04-arm
              lib: libusbdmx.so
            - os: windows-latest
              lib: usbdmx64.dll
              make_extra_args: "-f Makefile-mingw64"
            - os: macos-15-intel
              lib: libusbdmx.dylib
            - os: macos-latest
              lib: libusbdmx.dylib
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    defaults:
        run:
            shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Install missing packages
      run: sudo apt-get update && sudo apt-get install libudev-dev -y
      if: ${{ runner.os == 'Linux' }}
    - name: Build
      run: make ${{ matrix.make_extra_args }} ${{ matrix.lib }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: DMXforDummies-${{ matrix.os }}-${{ github.job }}
        path: |
          libusbdmx.so
          libusbdmx.dylib
          usbdmx64.dll
          *.o
          **/*.o
          50-usbdmx.rules
          README.md
          LICENSE*.txt